/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations.index'
import { Route as RecurringMeetingsIdRouteImport } from './routes/recurring-meetings.$id'
import { Route as OrganizationsIdRouteImport } from './routes/organizations.$id'

const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationsRoute,
} as any)
const RecurringMeetingsIdRoute = RecurringMeetingsIdRouteImport.update({
  id: '/recurring-meetings/$id',
  path: '/recurring-meetings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIdRoute = OrganizationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrganizationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/organizations/$id': typeof OrganizationsIdRoute
  '/recurring-meetings/$id': typeof RecurringMeetingsIdRoute
  '/organizations/': typeof OrganizationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/recurring-meetings/$id': typeof RecurringMeetingsIdRoute
  '/organizations': typeof OrganizationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/organizations/$id': typeof OrganizationsIdRoute
  '/recurring-meetings/$id': typeof RecurringMeetingsIdRoute
  '/organizations/': typeof OrganizationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/organizations'
    | '/organizations/$id'
    | '/recurring-meetings/$id'
    | '/organizations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/organizations/$id'
    | '/recurring-meetings/$id'
    | '/organizations'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/organizations'
    | '/organizations/$id'
    | '/recurring-meetings/$id'
    | '/organizations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OrganizationsRoute: typeof OrganizationsRouteWithChildren
  RecurringMeetingsIdRoute: typeof RecurringMeetingsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/recurring-meetings/$id': {
      id: '/recurring-meetings/$id'
      path: '/recurring-meetings/$id'
      fullPath: '/recurring-meetings/$id'
      preLoaderRoute: typeof RecurringMeetingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$id': {
      id: '/organizations/$id'
      path: '/$id'
      fullPath: '/organizations/$id'
      preLoaderRoute: typeof OrganizationsIdRouteImport
      parentRoute: typeof OrganizationsRoute
    }
  }
}

interface OrganizationsRouteChildren {
  OrganizationsIdRoute: typeof OrganizationsIdRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
}

const OrganizationsRouteChildren: OrganizationsRouteChildren = {
  OrganizationsIdRoute: OrganizationsIdRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
}

const OrganizationsRouteWithChildren = OrganizationsRoute._addFileChildren(
  OrganizationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OrganizationsRoute: OrganizationsRouteWithChildren,
  RecurringMeetingsIdRoute: RecurringMeetingsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
