/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations.index'
import { Route as RecurringMeetingsIdRouteImport } from './routes/recurring-meetings.$id'
import { Route as OrganizationsIdRouteImport } from './routes/organizations.$id'
import { Route as MeetingsIdRouteImport } from './routes/meetings.$id'

const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationsRoute,
} as any)
const RecurringMeetingsIdRoute = RecurringMeetingsIdRouteImport.update({
  id: '/recurring-meetings/$id',
  path: '/recurring-meetings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIdRoute = OrganizationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrganizationsRoute,
} as any)
const MeetingsIdRoute = MeetingsIdRouteImport.update({
  id: '/meetings/$id',
  path: '/meetings/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/review': typeof ReviewRoute
  '/meetings/$id': typeof MeetingsIdRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/recurring-meetings/$id': typeof RecurringMeetingsIdRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/review': typeof ReviewRoute
  '/meetings/$id': typeof MeetingsIdRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/recurring-meetings/$id': typeof RecurringMeetingsIdRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/review': typeof ReviewRoute
  '/meetings/$id': typeof MeetingsIdRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/recurring-meetings/$id': typeof RecurringMeetingsIdRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invitations'
    | '/login'
    | '/organizations'
    | '/review'
    | '/meetings/$id'
    | '/organizations/$id'
    | '/recurring-meetings/$id'
    | '/organizations/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invitations'
    | '/login'
    | '/review'
    | '/meetings/$id'
    | '/organizations/$id'
    | '/recurring-meetings/$id'
    | '/organizations'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/invitations'
    | '/login'
    | '/organizations'
    | '/review'
    | '/meetings/$id'
    | '/organizations/$id'
    | '/recurring-meetings/$id'
    | '/organizations/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvitationsRoute: typeof InvitationsRoute
  LoginRoute: typeof LoginRoute
  OrganizationsRoute: typeof OrganizationsRouteWithChildren
  ReviewRoute: typeof ReviewRoute
  MeetingsIdRoute: typeof MeetingsIdRoute
  RecurringMeetingsIdRoute: typeof RecurringMeetingsIdRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/recurring-meetings/$id': {
      id: '/recurring-meetings/$id'
      path: '/recurring-meetings/$id'
      fullPath: '/recurring-meetings/$id'
      preLoaderRoute: typeof RecurringMeetingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$id': {
      id: '/organizations/$id'
      path: '/$id'
      fullPath: '/organizations/$id'
      preLoaderRoute: typeof OrganizationsIdRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/meetings/$id': {
      id: '/meetings/$id'
      path: '/meetings/$id'
      fullPath: '/meetings/$id'
      preLoaderRoute: typeof MeetingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrganizationsRouteChildren {
  OrganizationsIdRoute: typeof OrganizationsIdRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
}

const OrganizationsRouteChildren: OrganizationsRouteChildren = {
  OrganizationsIdRoute: OrganizationsIdRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
}

const OrganizationsRouteWithChildren = OrganizationsRoute._addFileChildren(
  OrganizationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvitationsRoute: InvitationsRoute,
  LoginRoute: LoginRoute,
  OrganizationsRoute: OrganizationsRouteWithChildren,
  ReviewRoute: ReviewRoute,
  MeetingsIdRoute: MeetingsIdRoute,
  RecurringMeetingsIdRoute: RecurringMeetingsIdRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
